# Directories
dir:
  build: 'build'
  content: 'src/content'
  deploy: 'deploy'
  layout: 'src/layout'
  source: 'src'
  media: 'src/assets'

# Package, no idea what this is used for
pkg: "<json:package.json>"

########################################
# Tasks
########################################

# Cleaning
clean:
  build: '<%= dir.build %>'
  deploy: '<%= dir.deploy %>'

# Static assets
copy:
  raw:
    files:
      - 
        cwd: "<%= dir.source %>/raw"
        dest: "<%= dir.deploy %>"
        expand: true
        src: ["**/*"]

  assets:
    files:
      -
        cwd: "<%= dir.media %>"
        dest: "<%= dir.deploy %>/assets"
        expand: true
        src: ["images/**/*", "icons/**/*"]

  literate_artifacts:
    files:
      -
        cwd: "<%= dir.content %>"
        dest: "<%= dir.deploy %>"
        expand: true
        src: ["lp/**/*.{coffee,pl,sh,md}"]

# Coffee
coffee:
  all:
    cwd: '<%= dir.source %>'
    dest: '<%= dir.build %>'
    expand: true
    ext: '.js'
    src: ['**/*.coffee']

# Stylus
stylus:
  all:
    files:
      -
        cwd: "<%= dir.media %>"
        dest: "<%= dir.deploy %>"
        expand: true
        ext: '.css'
        src: "**/*.styl"

# Jade
jade:
  all:
    files: 
      -  
        cwd: "<%= dir.layout %>"
        dest: "<%= dir.build %>"
        expand: true
        ext: '.hbs'
        pretty: true
        src: "**/*.jade"

# Markdown + Handlebars + YFM rendering
render:
  words:
    index: '<%= dir.build %>/postlist.hbs'
    template: '<%= dir.build %>/page.hbs'
    files:
      -
        expand: true
        cwd: "<%= dir.content %>/words"
        src: ['*.md']
        dest: '<%= dir.deploy %>/words'
        ext: '/index.html'
  games:
    index: '<%= dir.build %>/projectlist.hbs'
    template: '<%= dir.build %>/project.hbs'
    files:
      -
        expand: true
        cwd: '<%= dir.content %>/projects'
        src: ['*.md', '!index.md']
        dest: '<%= dir.deploy %>/projects'
        ext: '/index.html'
  pages:
    template: '<%= dir.build %>/page.hbs'
    files:
      -
        expand: true
        cwd: "<%= dir.content %>"
        src: ['bio.md', 'resume.md']
        dest: '<%= dir.deploy %>'
        ext: '/index.html'
  resume:
    template: '<%= dir.build %>/page.hbs'
    files: 
      -
        src: ["<%= dir.content %>/resume/src/content.tex"]
        dest: '<%= dir.deploy %>/resume.html'
  tunes:
    template: '<%= dir.build%>/tunes.hbs'
    files:
      -
        expand: true
        cwd: "<%= dir.content %>"
        src: ['tunes.md']
        dest: '<%= dir.deploy %>'
        ext: '/index.html'


  literate_programming:
    literate: true
    template: '<%= dir.build %>/page.hbs'
    files:
      -
        expand: true
        cwd: "<%= dir.content %>"
        src: ['lp/**.md']
        dest: '<%= dir.deploy %>'
        ext: '.html'


  tidbits:
    template: '<%= dir.build %>/default.hbs'
    files:
      - 
        expand: true
        cwd: "<%= dir.content %>"
        src: ['tidbits/index.md']
        dest: '<%= dir.deploy %>'
        ext: '.html'

  root:
    template: '<%= dir.build %>/homepage.hbs'
    files:
      -
        expand: true
        cwd: "<%= dir.content %>"
        src: "index.md"
        dest: '<%= dir.deploy %>'
        ext: '.html'

# Serving up http
connect:
  server:
    options:
      base: "<%= dir.deploy %>"
      livereload: true

# Watch for changes and live reload
watch:
  options: {livereload: true}
  all:
    files: ["<%= dir.source %>/**/*.*"]
    tasks: ['build']


